CIBLE = main
SRCS =  Main.cpp 
LIBS =  -lglut32 -lGLU32 -lopengl32 -lm 

CC = g++
CPP = g++

FLAGS = -Wall -O2 

CFLAGS = $(FLAGS)
CXXFLAGS = $(FLAGS)

OBJS = $(SRCS:.cpp=.o)   

$(CIBLE): $(OBJS)
	g++ $(LDFLAGS) -o $(CIBLE) $(OBJS) $(LIBS)
clean:
	rm -f  *~  $(CIBLE) $(OBJS)

Main.o: Main.cpp



